services:
  backend:
    container_name: backend
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db
      TZ: Asia/Taipei
    volumes:
      - ./data:/data/db
