services:
  backend:
    container_name: backend
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
