services:
  backend:
    container_name: hackathon2024-backend
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - SECRET=very_secret_string
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
  mongodb:
    image: mongo:4.4.6
    container_name: hackathon2024-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db
      TZ: Asia/Taipei
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
